name: flutter_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1  # Versiyon numarası

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dotlottie_loader: ^0.0.4
  flutter_secure_storage: ^9.2.2
  go_router: ^14.6.1
  google_fonts: ^6.2.1  # Güncel sürüm
  lottie: ^3.1.3
  shared_preferences: ^2.0.17
  url_launcher: ^6.0.9
  path_provider: ^2.0.15  # Eklenen bağımlılık

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.14.3  # İkon oluşturma için bağımlılık

flutter_icons:
  android: true
  ios: true
  web: true
  generate: true  # İkonlar otomatik olarak oluşturulacak
  image_path: "assets/icons/app_icon.png"  # İkon dosyasının yolu

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/onboarding_images/
    - assets/images/hesaplama_araci/
    - assets/icons/
    - assets/languages/
    - assets/motions/
